### ISSUE TITLE
getclubhouseinvite.boxpiper.com in 512KB club

### ISSUE THREAD

**Issue by sanmak** [kevquirk/512kb.club#181] opened 2021-01-19 15:08 UTC
* **https://getclubhouseinvite.boxpiper.com/**
* **https://gtmetrix.com/reports/getclubhouseinvite.boxpiper.com/PFVoPkwP/**
* **148.1 KB**

Please fill in the following template too. It will speed up getting your site added. The example below uses `example.com` as the domain and an uncompressed page size of `81.4 KB`.

**Note: Please fill in the uncompressed size on line 1 (`--data-size`) AND line 2**

```
<li>
  <span class="before" style="--data-size:148.1;"></span>
  <span class="after">148.1 KB</span>
  <a class="site" target="blank" href="https://getclubhouseinvite.boxpiper.com/">https://getclubhouseinvite.boxpiper.com/</a>
</li>
```

**Comment by kevquirk** [comment] 2021-01-20 15:49
Trying to understand what this site is?

**Comment by sanmak** [comment] 2021-01-20 17:27
It's for promoting Clubhouse invites.

**Comment by kevquirk** [comment] 2021-01-22 08:58
...but what is clubhouse?

**Comment by kevquirk** [comment] 2021-01-22 09:05
Already added clubhouse under #187, this is a duplicate of the same/similar page within the same site. Won't be adding this.

**Closed by kevquirk** 2021-01-22 09:05 UTC
