### ISSUE TITLE
portfolio.yeetpc.com

### ISSUE THREAD

**Issue by Rav4s** [kevquirk/512kb.club#317] opened 2021-04-04 23:04 UTC
Link to GTMetrix results: https://gtmetrix.com/reports/portfolio.yeetpc.com/3QU1gq0a/

```
- domain: portfolio.yeetpc.com
  url: http://portfolio.yeetpc.com/
  size: 199.9
```

**Comment by kevquirk** [comment] 2021-04-06 15:01
Duplicate of #316

**Closed by kevquirk** 2021-04-06 15:01 UTC
